---
- name: Converge
  hosts: all
  become: yes
  roles:
    - role: Docker
      vars:
        mockserver_docker_namespace: mimo
        mockserver_docker_files_to_copy:
          - mimo_statics.conf
        mockserver_docker_networks:
          - mimo
        mockserver_docker_volumes:
          - mimo
        mockserver_docker_images:
          mockserver:
            name: api
            image: ldelelis/mockserver
            tag: develop
            networks:
              - name: mimo
            mounts:
              - source: mimo
                target: /usr/src/app/mockserver/static
            labels:
              traefik.frontend.passHostHeaders: "true"
              traefik.http.routers.mockserver.rule: Host(`dev.mimo.ldelelis.dev`)
            env:
              DATABASE_URL: "{{ lookup('env', 'MIMO_DATABASE_URL')}}"
            command: "gunicorn -w 4 --bind 0.0.0.0:8000 --log-level error --chdir ./mockserver mockserver.wsgi"
          celery:
            name: tasks
            image: ldelelis/mockserver
            tag: develop
            networks:
              - name: mimo
            env:
              CELERY_BROKER_URL: "{{ lookup('env', 'MIMO_REDIS_URL') }}"
            command: "celery worker -A mockserver --workdir mockserver -l info"
          redis:
            name: cache
            image: redis
            tag: 5
            networks:
              - name: mimo
          traefik:
            name: webserver
            image: traefik
            tag: v2.0
            ports:
              - "8000:80"
            networks:
              - name: mimo
            volumes:
              - "/var/run/docker.sock:/var/run/docker.sock"
            command: "--providers.docker"
          nginx:
            name: statics-webserver
            image: nginx
            tag: alpine
            networks:
              - name: mimo
            volumes:
              - "/usr/mimo_statics.conf:/etc/nginx/conf.d/default.conf"
            mounts:
              - source: mimo
                target: /static
            labels:
              traefik.frontend.passHostHeaders: "true"
              traefik.http.routers.nginx.rule: Host(`dev.mimo.ldelelis.dev`) && PathPrefix(`/static`)
            command: "nginx -g 'daemon off;'"
        ansible_python_interpreter: /usr/bin/python3
