---
- name: Adds certbot repositories
  apt_repository:
    repo: ppa:certbot/certbot
    state: present
    update_cache: yes

- name: Ensures Certbot is installed
  apt:
    name: python-certbot-nginx
    state: present

- name: Ensure periodic certificate checks are running
  cron:
    name: certbot renewal
    job: certbot renew
    special_time: daily
    state: present
