---
- hosts: apiservers
  become: yes
  gather_facts: yes

  roles:
    - role: Resolvconf
      tags: [ never, packer, resolvconf ]
    - role: Nginx
      tags: [ never, packer, nginx ]
      vars:
        mockserver_nginx_hosts:
          mimo:
    - role: Docker
      tags: [ never, packer, docker ]
      vars:
        mockserver_docker_images:
            mockserver:
                name: mimo-api
                image: ldelelis/mockserver
                tag: develop
                ports:
                  - "8000:8000"
                env:
                  DATABASE_URL: "postgres://postgres:testpassword@db.internal.mimo:5432/mocks-api"
                command: "gunicorn -w 4 --bind 0.0.0.0:8000 --log-level error --chdir ./mockserver mockserver.wsgi"
    - role: Letsencrypt
      tags: [ never, packer, letsencrypt ]
