---
- hosts: dev
  become: yes
  gather_facts: yes

  roles:
    - role: Nginx
      tags: [ never, packer, nginx ]
    - role: Docker
      tags: [ never, packer, docker ]
      vars:
        mockserver_docker_images:
            mockserver:
                name: mimo-api
                image: ldelelis/mockserver
                tag: develop
                ports:
                  - "8000:8000"
