---
- name: Ensure resolvconf dependencies are installed
  apt:
    name: ifupdown
    state: present
    update_cache: yes

- name: Ensure resolvconf is installed
  apt:
    name: resolvconf
    state: present

- name: Ensure resolvconf internal configuraion is installed
  template:
    src: head.j2
    dest: /etc/resolvconf/resolv.conf.d/head
  notify:
    - Restart resolvconf